# Site settings
title: My Astro Research
email: astroskii@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    This site records my (part of ) research. I'm trying to post everyday without excuses. Let's see what will happen ...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://karlan.github.io/" # the base hostname & protocol for your site
twitter_username: JianweiLyu
github_username:  karlan
weibo_username:  karlan
douban_username:  karlan

# Build settings
markdown: kramdown
