# Site settings
title: The Stars at Full
email: astroskii@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    This site is about astronomy research and other interesting stuffs. Feel free to contact me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://karlan.github.io/" # the base hostname & protocol for your site
# twitter_username: JianweiLyu
github_username:  karlan
weibo_username:  karlan
douban_username:  karlan

# Build settings
markdown: kramdown
